# --- !Ups

CREATE TABLE `CAT` (	`NAME` VARCHAR(50) NOT NULL,	`COLOR` VARCHAR(50) NULL,	PRIMARY KEY (`NAME`));
CREATE TABLE `DOG` (	`NAME` VARCHAR(50) NOT NULL,	`COLOR` VARCHAR(50) NULL,	PRIMARY KEY (`NAME`));

# --- !Downs

drop table "CAT";
drop table "DOG";
