# --- !UPS

CREATE TABLE TB_USER (
  ID                        BIGINT NOT NULL AUTO_INCREMENT,
  NAME                      VARCHAR(255),
  LOGIN_ID                  VARCHAR(255),
  PASSWORD                  VARCHAR(255),
  PASSWORD_SALT             VARCHAR(255),
  EMAIL                     VARCHAR(255),
  AVATAR_URL                VARCHAR(255),
  REMEMBER_ME               BOOLEAN,
  DATE                      TIMESTAMP,
  CONSTRAINT PK_TB_USER PRIMARY KEY (ID))
;

CREATE TABLE TB_BOARD (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	CONTENT TEXT NULL,
	WRITER_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	WRITER_ID INT(11) NULL DEFAULT NULL,
	WRITER_IP CHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


# --- !DOWNS

DROP TABLE TB_USER;
DROP TABLE TB_BOARD;
